var res = {
    MenuBackground : "res/images/menu.jpg",
    HowToSingleBackground : "res/images/howToSingle.jpg",
    HowToMultiBackground : "res/images/howToMulti.jpg",
    Background_png : "res/images/background.png",
    TitleText : "res/images/popori.png",
    SingleText1 : "res/images/singleplayer1.png",
    SingleText2 : "res/images/singleplayer2.png",
    MultiText1 : "res/images/multiplayer1.png",
    MultiText2 : "res/images/multiplayer2.png",
    HowTo1Text : "res/images/howTo1.png",
    HowTo2Text : "res/images/howTo2.png",
    BackToMenu1 : "res/images/backToMenu1.png",
    BackToMenu2 : "res/images/backToMenu2.png",
    BackButton1 : "res/images/back1.png",
    RetryButton1 : "res/images/retry1.png",
    RetryButton2 : "res/images/retry2.png",
    Player1_pic : "res/images/player1.png",
    Player2_pic : "res/images/player2.png",
    Cream_pic : "res/images/food/cream.png",
    Croissant_pic : "res/images/food/croissant.png",
    Donut_pic : "res/images/food/donut.png",
    Hamburger_pic : "res/images/food/hamburger.png",
    Hotdog_pic : "res/images/food/hotdog.png",
    Macaroon_pic : "res/images/food/macaroon.png",
    Pizza_pic : "res/images/food/pizza.png",
    Sandwich_pic : "res/images/food/sandwich.png",
    Unji_pic : "res/images/food/unji.png",
    Power_pic : "res/images/item/power.png",
    Shield_pic : "res/images/item/shield.png",
    Speed_pic : "res/images/item/speed.png",
    Slow_pic : "res/images/item/slow.png",
    Life_pic : "res/images/item/life.png",
    ArrowLeft_pic : "res/images/arrowleft.png",
    ArrowRight_pic : "res/images/arrowright.png",
    ArrowDown_pic : "res/images/arrowdown.png",
    Menu_song : "res/songs/menusong.mp3",
    Eat_effect : "res/songs/eat.mp3",
    GetItem_effect : "res/songs/getitem.wav",
    HitArrow_effect : "res/songs/hitarrow.mp3",
    Game_song : "res/songs/gamesong.mp3",
    Collide_effect : "res/songs/collide.mp3"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}